// ===================================================
//  TravelAssistant — Bilingual Language Script
//  Supports: English (en) | Bengali (bn)
// ===================================================

const translations = {
  en: {
    /* ── NAV ── */
    "nav-home":         "Home",
    "nav-destinations": "Destinations",
    "nav-weather":      "Weather Preference",
    "nav-budget":       "Budget Planner",
    "nav-seasonal":     "Seasonal Specials",
    "nav-contact":      "Contact",
    "nav-about":        "About Us",
    "nav-matchmaker":   "Matchmaker",
    "nav-packing":      "Packing Assistant",

    /* ── AUTH PAGE ── */
    "auth-subtitle":      "Access your smart travel planner",
    "tab-login":          "Login",
    "tab-signup":         "Sign Up",
    "tab-guest":          "Guest",
    "label-email":        "Email",
    "label-password":     "Password",
    "label-fullname":     "Full Name",
    "btn-login":          "Login",
    "btn-signup":         "Create Account",
    "placeholder-email":  "Enter email",
    "placeholder-pass":   "Enter password",
    "placeholder-newpass":"Create password",
    "placeholder-name":   "Enter full name",

    /* ── HOME ── */
    "home-subtitle":       "Your Smart Journey Starts Here",
    "home-h2":             "Welcome to TravelAssistant 2026",
    "home-intro":          "We help you plan your perfect getaway by matching your favourite weather with the best destinations across India and the world. Whether you are looking for a snowy retreat or a tropical beach, we have you covered.",
    "feat-explore-title":  "Explore",
    "feat-explore-desc":   "Browse through our curated list of top-rated destinations.",
    "feat-weather-title":  "Weather",
    "feat-weather-desc":   "Filter locations based on the climate you love most.",
    "feat-budget-title":   "Budget",
    "feat-budget-desc":    "Estimate your 2026 trip costs with our smart calculator.",
    "home-highlight":      "Ready to explore? Start by viewing our",
    "home-highlight-link": "Destination List",
    "footer-copy":         "© 2026 TravelAssistant Global. All rights reserved.",

    /* ── PAGE 2 – DESTINATIONS ── */
    "dest-subtitle":      "Complete Destination List (24 Places)",
    "dest-h2-culture":    "Culture & History",
    "dest-h2-adventure":  "Adventure & Mountains",
    "dest-h2-beach":      "Beach & Relaxation",
    "dest-h2-city":       "City & Urban Exploration",
    "dest-climate-label": "Climate:",

    /* ── PAGE 3 – WEATHER ── */
    "weather-subtitle":     "Weather Based Destination Finder",
    "weather-h2":           "Select Weather Type",
    "weather-opt-default":  "-- Choose Weather --",
    "weather-opt-hot":      "Hot / Tropical",
    "weather-opt-pleasant": "Mild / Pleasant",
    "weather-opt-cold":     "Cold / Snow",
    "weather-opt-rainy":    "Humid / Rainy",
    "weather-btn":          "Show Places",
    "weather-result-hot":   "Hot / Tropical Destinations",
    "weather-result-pleasant": "Mild / Pleasant Destinations",
    "weather-result-cold":  "Cold / Snow Destinations",
    "weather-result-rainy": "Humid / Rainy Destinations",

    /* ── PAGE 4 – BUDGET ── */
    "budget-subtitle":     "Plan Your Expenses (₹ INR)",
    "budget-h2":           "Auto-Budget Calculator",
    "budget-intro":        "Select a destination to auto-fill estimated 2026 costs.",
    "budget-label-dest":   "Select Destination",
    "budget-label-flight": "Flight / Travel Cost (₹)",
    "budget-label-hotel":  "Hotel per Night (₹)",
    "budget-label-nights": "Number of Nights",
    "budget-label-daily":  "Daily Food + Local Travel (₹)",
    "budget-total-title":  "Estimated Total Budget",
    "budget-btn-reset":    "Reset",
    "budget-avg-per-day":  "Avg per day: ₹",

    /* ── PAGE 5 – SEASONAL ── */
    "seasonal-h1":       "Seasonal Specials",
    "seasonal-subtitle": "Unique experiences for 2026",
    "seasonal-h2":       "Featured This Month",
    "season-best-time":         "Best Time:",
    "season-badge-adventure":   "Adventure",
    "season-badge-culture":     "Culture",
    "season-badge-romantic":    "Romantic",
    "season-badge-relaxation":  "Relaxation",
    "season-badge-wellness":    "Wellness",
    "season-badge-heritage":    "Heritage",
    "season-badge-skiing":      "Skiing",
    "season-badge-luxury":      "Luxury",
    "season-badge-nature":      "Nature",
    "season-ladakh-name":    "Leh Ladakh, India",
    "season-ladakh-time":    "June to September",
    "season-ladakh-desc":    "Experience high-altitude monasteries and the mesmerizing Pangong Lake.",
    "season-tokyo-name":     "Tokyo, Japan",
    "season-tokyo-time":     "March to April",
    "season-tokyo-desc":     "Witness the iconic cherry blossoms and vibrant city life.",
    "season-paris-name":     "Paris, France",
    "season-paris-time":     "June to August",
    "season-paris-desc":     "Enjoy the \"City of Lights\" during the beautiful summer season.",
    "season-santorini-name": "Santorini, Greece",
    "season-santorini-time": "April to October",
    "season-santorini-desc": "Stunning white-washed architecture overlooking the Aegean Sea.",
    "season-bali-name":      "Bali, Indonesia",
    "season-bali-time":      "May to September",
    "season-bali-desc":      "Spiritual retreats and lush tropical rice terraces in Ubud.",
    "season-jaipur-name":    "Jaipur, India",
    "season-jaipur-time":    "November to February",
    "season-jaipur-desc":    "Explore grand palaces and historic forts in the Royal Pink City.",
    "season-zermatt-name":   "Zermatt, Switzerland",
    "season-zermatt-time":   "December to March",
    "season-zermatt-desc":   "World-class winter sports at the base of the mighty Matterhorn.",
    "season-positano-name":  "Positano, Italy",
    "season-positano-time":  "May to September",
    "season-positano-desc":  "Stunning coastal cliffs and luxury Italian seaside living.",
    "season-munnar-name":    "Munnar, India",
    "season-munnar-time":    "September to March",
    "season-munnar-desc":    "Relax among rolling tea plantations and mist-covered hills.",
    "season-reykjavik-name": "Reykjavik, Iceland",
    "season-reykjavik-time": "September to March",
    "season-reykjavik-desc": "The perfect spot to witness the magical Northern Lights.",

    /* ── PAGE 6 – CONTACT ── */
    "contact-subtitle":           "Contact Us",
    "contact-h2":                 "Get In Touch",
    "contact-intro":              "Have questions about your 2026 travel plans? Our team is ready to help you find the perfect climate and budget for your next adventure.",
    "contact-email-lbl":          "Email Address",
    "contact-phone-lbl":          "Phone Number",
    "contact-office-lbl":         "Office Location",
    "contact-fname":              "Full Name",
    "contact-emailid":            "Email ID",
    "contact-message":            "Message",
    "contact-message-placeholder":"How can we help you?",
    "contact-btn":                "Send Message",
    "contact-highlight":          "Want to see where to go? Check out the",
    "contact-highlight-link":     "Destination List",

    /* ── PAGE 7 – ABOUT ── */
    "about-subtitle":       "Why Choose Us",
    "about-h2":             "Your Smart Travel Companion",
    "about-intro":          "TravelAssistant is built for travelers who want clarity, comfort, and confidence while planning their journeys.",
    "about-feat1-title":    "🌦 Weather-Based Planning",
    "about-feat1-desc":     "Choose destinations that match your preferred climate.",
    "about-feat2-title":    "💰 Smart Budget Estimation",
    "about-feat2-desc":     "Our budget planner provides realistic cost estimates in INR.",
    "about-feat3-title":    "🌍 Curated Destinations",
    "about-feat3-desc":     "We carefully curate popular and reliable destinations.",
    "about-feat4-title":    "📅 Seasonal Recommendations",
    "about-feat4-desc":     "Discover destinations best visited during specific seasons.",
    "about-feat5-title":    "🚀 Easy & User-Friendly",
    "about-feat5-desc":     "Simple navigation, clean design and fast access to information.",
    "about-feat6-title":    "🔓 Guest-Friendly Access",
    "about-feat6-desc":     "Explore destinations and tools without mandatory signup.",
    "about-highlight":      "Start planning smarter — explore our",
    "about-highlight-link": "Destinations",

    /* ── PAGE 8 – MATCHMAKER ── */
    "match-subtitle":       "Destination Matchmaker",
    "match-h2":             "Find Your Perfect 2026 Trip",
    "match-intro":          "Answer three questions and we'll find a destination that fits you best.",
    "match-q1":             "1. What is your primary goal?",
    "match-opt-culture":    "History & Culture",
    "match-opt-adventure":  "Adventure & Nature",
    "match-opt-relax":      "Relaxation & Beaches",
    "match-opt-urban":      "City Life",
    "match-q2":             "2. Preferred Climate?",
    "match-opt-hot":        "Hot / Tropical",
    "match-opt-mild":       "Mild / Pleasant",
    "match-opt-cold":       "Cold / Snow",
    "match-q3":             "3. Travel Distance?",
    "match-opt-domestic":   "Within India",
    "match-opt-intl":       "International",
    "match-btn":            "Match Me!",
    "match-result-h2":      "It's a Match!",
    "match-no-results-h3":  "No matching destination found 😕",
    "match-no-results-p":   "Please try changing your preferences.",
    "match-check-budget":   "Check Budget",

    /* ── PAGE 10 – PACKING ── */
    "pack-subtitle":     "Your Smart Journey Starts Here",
    "pack-h2":           "Smart Packing Assistant",
    "pack-dest-label":   "Destination:",
    "pack-dest-none":    "Not Selected",
    "pack-label-days":   "Trip Duration",
    "pack-opt-3days":    "2–3 Days",
    "pack-opt-5days":    "4–6 Days",
    "pack-opt-8days":    "7+ Days",
    "pack-label-climate":"Climate",
    "pack-opt-hot":      "Hot / Tropical",
    "pack-opt-mild":     "Mild / Pleasant",
    "pack-opt-cold":     "Cold / Snow",
    "pack-label-type":   "Trip Type",
    "pack-opt-domestic": "Domestic",
    "pack-opt-intl":     "International",
    "pack-btn":          "Generate Packing List",
    "pack-checklist-h2": "Your Packing Checklist",

    /* ── PACKING CATEGORIES ── */
    "pack-cat-clothing":   "👕 Clothing",
    "pack-cat-essentials": "🎒 Essentials & Documents",
    "pack-cat-health":     "🩺 Health & Safety",
    "pack-cat-extras":     "✨ Extras",

    /* ── PACKING ITEMS ── */
    "pack-item-comfortable":  "Comfortable outfits",
    "pack-item-sleepwear":    "Sleepwear",
    "pack-item-innerwear":    "Innerwear",
    "pack-item-cotton":       "Cotton clothes",
    "pack-item-cap":          "Cap / Hat",
    "pack-item-sunglasses":   "Sunglasses",
    "pack-item-jacket":       "Light jacket",
    "pack-item-casual":       "Casual wear",
    "pack-item-heavy-jacket": "Jackets",
    "pack-item-thermals":     "Thermals",
    "pack-item-gloves":       "Gloves",
    "pack-item-socks":        "Woolen socks",
    "pack-item-phone":        "Mobile phone",
    "pack-item-charger":      "Charger",
    "pack-item-powerbank":    "Power bank",
    "pack-item-passport":     "Passport",
    "pack-item-visa":         "Visa",
    "pack-item-sim":          "International SIM",
    "pack-item-footwear":     "Extra footwear",
    "pack-item-laundry":      "Laundry bag",
    "pack-item-medicine":     "Basic medicines",
    "pack-item-firstaid":     "First-aid kit",
    "pack-item-sunscreen":    "Sunscreen",
    "pack-item-insect":       "Insect repellent",
    "pack-item-coldcream":    "Cold cream",
    "pack-item-lipbalm":      "Lip balm",
    "pack-item-camera":       "Camera",
    "pack-item-docs":         "Travel documents",
    "pack-item-snacks":       "Snacks",
    "pack-item-swimwear":     "Swimwear",
    "pack-item-towel":        "Towel",
    "pack-item-tickets":      "Flight Tickets",
    "pack-item-hotel-conf":   "Hotel Booking Confirmation",
    "pack-item-id-card":      "Aadhaar Card / Voter ID",
    "pack-item-insurance":    "Travel Insurance",

    /* ── DESTINATION NAMES, DESCS & CLIMATES ── */
    "agra-name":"Agra, India", "agra-desc":"Home of the Taj Mahal.", "agra-climate":"Hot & Dry",
    "paris-name":"Paris, France", "paris-desc":"Eiffel Tower, museums and café culture.", "paris-climate":"Pleasant",
    "rome-name":"Rome, Italy", "rome-desc":"Colosseum, Vatican and ancient ruins.", "rome-climate":"Mild",
    "kyoto-name":"Kyoto, Japan", "kyoto-desc":"Temples, cherry blossoms and traditions.", "kyoto-climate":"Mild",
    "kolkata-name":"Kolkata, India", "kolkata-desc":"Colonial architecture and cultural hub.", "kolkata-climate":"Humid",
    "athens-name":"Athens, Greece", "athens-desc":"Birthplace of Western civilization.", "athens-climate":"Sunny",
    "manali-name":"Manali, India", "manali-desc":"Snow sports and trekking routes.", "manali-climate":"Cold",
    "kashmir-name":"Kashmir, India", "kashmir-desc":"Dal Lake and snow valleys.", "kashmir-climate":"Cold",
    "swissalps-name":"Swiss Alps, Switzerland", "swissalps-desc":"Ski resorts and glaciers.", "swissalps-climate":"Cold",
    "ladakh-name":"Leh-Ladakh, India", "ladakh-desc":"High-altitude desert landscapes.", "ladakh-climate":"Cold",
    "queenstown-name":"Queenstown, New Zealand", "queenstown-desc":"Adventure capital of the world.", "queenstown-climate":"Mild",
    "zermatt-name":"Zermatt, Switzerland", "zermatt-desc":"Views of Matterhorn mountain.", "zermatt-climate":"Cold",
    "goa-name":"Goa, India", "goa-desc":"Beaches and nightlife.", "goa-climate":"Hot & Humid",
    "maldives-name":"Maldives", "maldives-desc":"Luxury overwater villas.", "maldives-climate":"Tropical",
    "phuket-name":"Phuket, Thailand", "phuket-desc":"Island hopping and beaches.", "phuket-climate":"Hot",
    "kerala-name":"Kerala Backwaters, India", "kerala-desc":"Houseboats and palm trees.", "kerala-climate":"Rainy & Pleasant",
    "hawaii-name":"Hawaii, USA", "hawaii-desc":"Volcanoes and surfing.", "hawaii-climate":"Warm",
    "bali-name":"Bali, Indonesia", "bali-desc":"Beaches and temples.", "bali-climate":"Tropical",
    "newyork-name":"New York, USA", "newyork-desc":"Skyscrapers and Broadway.", "newyork-climate":"Varies",
    "mumbai-name":"Mumbai, India", "mumbai-desc":"Bollywood and street markets.", "mumbai-climate":"Hot",
    "london-name":"London, UK", "london-desc":"Palaces and museums.", "london-climate":"Cool",
    "delhi-name":"Delhi, India", "delhi-desc":"Historic forts and markets.", "delhi-climate":"Hot",
    "singapore-name":"Singapore", "singapore-desc":"Clean modern city and gardens.", "singapore-climate":"Hot",
    "dubai-name":"Dubai, UAE", "dubai-desc":"Skyscrapers and desert safari.", "dubai-climate":"Hot"
  },

  bn: {
    /* ── NAV ── */
    "nav-home":         "হোম",
    "nav-destinations": "গন্তব্য তালিকা",
    "nav-weather":      "আবহাওয়া পছন্দ",
    "nav-budget":       "বাজেট পরিকল্পক",
    "nav-seasonal":     "মৌসুমি বিশেষ",
    "nav-contact":      "যোগাযোগ",
    "nav-about":        "আমাদের সম্পর্কে",
    "nav-matchmaker":   "ম্যাচমেকার",
    "nav-packing":      "প্যাকিং সহায়ক",

    /* ── AUTH PAGE ── */
    "auth-subtitle":      "আপনার স্মার্ট ট্রাভেল প্ল্যানারে প্রবেশ করুন",
    "tab-login":          "লগইন",
    "tab-signup":         "নিবন্ধন",
    "tab-guest":          "অতিথি",
    "label-email":        "ইমেইল",
    "label-password":     "পাসওয়ার্ড",
    "label-fullname":     "পুরো নাম",
    "btn-login":          "লগইন করুন",
    "btn-signup":         "অ্যাকাউন্ট তৈরি করুন",
    "placeholder-email":  "ইমেইল লিখুন",
    "placeholder-pass":   "পাসওয়ার্ড লিখুন",
    "placeholder-newpass":"পাসওয়ার্ড তৈরি করুন",
    "placeholder-name":   "পুরো নাম লিখুন",

    /* ── HOME ── */
    "home-subtitle":       "আপনার স্মার্ট যাত্রা এখানেই শুরু",
    "home-h2":             "TravelAssistant 2026-এ স্বাগতম",
    "home-intro":          "আমরা আপনার পছন্দের আবহাওয়ার সাথে ভারত ও বিশ্বের সেরা গন্তব্যগুলো মেলাতে সাহায্য করি।",
    "feat-explore-title":  "অন্বেষণ করুন",
    "feat-explore-desc":   "আমাদের কিউরেটেড শীর্ষ গন্তব্য তালিকা দেখুন।",
    "feat-weather-title":  "আবহাওয়া",
    "feat-weather-desc":   "আপনার পছন্দের জলবায়ু অনুযায়ী স্থান ফিল্টার করুন।",
    "feat-budget-title":   "বাজেট",
    "feat-budget-desc":    "আমাদের স্মার্ট ক্যালকুলেটরে ২০২৬ সালের ভ্রমণ খরচ আনুমান করুন।",
    "home-highlight":      "অন্বেষণ করতে প্রস্তুত? আমাদের দেখুন",
    "home-highlight-link": "গন্তব্য তালিকা",
    "footer-copy":         "© ২০২৬ TravelAssistant Global। সর্বস্বত্ব সংরক্ষিত।",

    /* ── PAGE 2 – DESTINATIONS ── */
    "dest-subtitle":      "সম্পূর্ণ গন্তব্য তালিকা (২৪টি স্থান)",
    "dest-h2-culture":    "সংস্কৃতি ও ইতিহাস",
    "dest-h2-adventure":  "অ্যাডভেঞ্চার ও পাহাড়",
    "dest-h2-beach":      "সৈকত ও বিশ্রাম",
    "dest-h2-city":       "শহর ও নগর অন্বেষণ",
    "dest-climate-label": "আবহাওয়া:",

    /* ── PAGE 3 – WEATHER ── */
    "weather-subtitle":     "আবহাওয়া ভিত্তিক গন্তব্য অনুসন্ধানকারী",
    "weather-h2":           "আবহাওয়ার ধরন নির্বাচন করুন",
    "weather-opt-default":  "-- আবহাওয়া বেছে নিন --",
    "weather-opt-hot":      "গরম / ক্রান্তীয়",
    "weather-opt-pleasant": "মৃদু / আনন্দদায়ক",
    "weather-opt-cold":     "ঠান্ডা / তুষার",
    "weather-opt-rainy":    "আর্দ্র / বৃষ্টিময়",
    "weather-btn":          "স্থানগুলো দেখুন",
    "weather-result-hot":   "গরম / ক্রান্তীয় গন্তব্য",
    "weather-result-pleasant": "মৃদু / আনন্দদায়ক গন্তব্য",
    "weather-result-cold":  "ঠান্ডা / তুষারময় গন্তব্য",
    "weather-result-rainy": "আর্দ্র / বৃষ্টিময় গন্তব্য",

    /* ── PAGE 4 – BUDGET ── */
    "budget-subtitle":     "আপনার খরচ পরিকল্পনা করুন (₹ INR)",
    "budget-h2":           "স্বয়ংক্রিয় বাজেট ক্যালকুলেটর",
    "budget-intro":        "আনুমানিক ২০২৬ খরচ স্বয়ংক্রিয়ভাবে পূরণ করতে একটি গন্তব্য নির্বাচন করুন।",
    "budget-label-dest":   "গন্তব্য নির্বাচন করুন",
    "budget-label-flight": "বিমান / যাতায়াত খরচ (₹)",
    "budget-label-hotel":  "প্রতি রাতে হোটেল (₹)",
    "budget-label-nights": "রাতের সংখ্যা",
    "budget-label-daily":  "দৈনিক খাবার + স্থানীয় যাতায়াত (₹)",
    "budget-total-title":  "আনুমানিক মোট বাজেট",
    "budget-btn-reset":    "রিসেট",
    "budget-avg-per-day":  "গড় প্রতিদিন: ₹",

    /* ── PAGE 5 – SEASONAL ── */
    "seasonal-h1":       "মৌসুমি বিশেষ",
    "seasonal-subtitle": "২০২৬ সালের অনন্য অভিজ্ঞতা",
    "seasonal-h2":       "এই মাসের বিশেষ আকর্ষণ",

    /* ── PAGE 6 – CONTACT ── */
    "contact-subtitle":       "যোগাযোগ করুন",
    "contact-h2":             "আমাদের সাথে যোগাযোগ করুন",
    "contact-intro":          "আপনার ২০২৬ ভ্রমণ পরিকল্পনা নিয়ে প্রশ্ন আছে?",
    "contact-email-lbl":      "ইমেইল ঠিকানা",
    "contact-phone-lbl":      "ফোন নম্বর",
    "contact-office-lbl":     "অফিসের অবস্থান",
    "contact-fname":          "পুরো নাম",
    "contact-emailid":        "ইমেইল আইডি",
    "contact-message":        "বার্তা",
    "contact-btn":            "বার্তা পাঠান",
    "contact-highlight":      "কোথায় যাবেন দেখতে চান? আমাদের দেখুন",
    "contact-highlight-link": "গন্তব্য তালিকা",

    /* ── PAGE 7 – ABOUT ── */
    "about-subtitle":       "কেন আমাদের বেছে নেবেন",
    "about-h2":             "আপনার স্মার্ট ভ্রমণ সঙ্গী",
    "about-intro":          "TravelAssistant সেই ভ্রমণকারীদের জন্য তৈরি যারা পরিকল্পনায় স্পষ্টতা ও আত্মবিশ্বাস চান।",
    "about-feat1-title":    "🌦 আবহাওয়াভিত্তিক পরিকল্পনা",
    "about-feat1-desc":     "আপনার পছন্দের জলবায়ু অনুযায়ী গন্তব্য বেছে নিন।",
    "about-feat2-title":    "💰 স্মার্ট বাজেট অনুমান",
    "about-feat2-desc":     "আমাদের বাজেট প্ল্যানার INR-তে বাস্তবসম্মত খরচের অনুমান দেয়।",
    "about-feat3-title":    "🌍 কিউরেটেড গন্তব্য",
    "about-feat3-desc":     "আমরা জনপ্রিয় ও নির্ভরযোগ্য গন্তব্যগুলো সাবধানে বেছে রাখি।",
    "about-feat4-title":    "📅 মৌসুমি সুপারিশ",
    "about-feat4-desc":     "নির্দিষ্ট মৌসুমে সেরা গন্তব্যগুলো আবিষ্কার করুন।",
    "about-feat5-title":    "🚀 সহজ ও ব্যবহারকারী-বান্ধব",
    "about-feat5-desc":     "সহজ নেভিগেশন ও দ্রুত তথ্য অ্যাক্সেস।",
    "about-feat6-title":    "🔓 অতিথি-বান্ধব অ্যাক্সেস",
    "about-feat6-desc":     "বাধ্যতামূলক নিবন্ধন ছাড়াই গন্তব্য অন্বেষণ করুন।",
    "about-highlight":      "স্মার্টভাবে পরিকল্পনা শুরু করুন — আমাদের দেখুন",
    "about-highlight-link": "গন্তব্য",

    /* ── PAGE 8 – MATCHMAKER ── */
    "match-subtitle":       "গন্তব্য ম্যাচমেকার",
    "match-h2":             "আপনার নিখুঁত ২০২৬ ভ্রমণ খুঁজে নিন",
    "match-intro":          "তিনটি প্রশ্নের উত্তর দিন এবং আমরা আপনার জন্য সেরা গন্তব্য খুঁজে বের করব।",
    "match-q1":             "১. আপনার প্রধান লক্ষ্য কী?",
    "match-opt-culture":    "ইতিহাস ও সংস্কৃতি",
    "match-opt-adventure":  "অ্যাডভেঞ্চার ও প্রকৃতি",
    "match-opt-relax":      "বিশ্রাম ও সৈকত",
    "match-opt-urban":      "শহুরে জীবন",
    "match-q2":             "২. পছন্দের জলবায়ু?",
    "match-opt-hot":        "গরম / ক্রান্তীয়",
    "match-opt-mild":       "মৃদু / আনন্দদায়ক",
    "match-opt-cold":       "ঠান্ডা / তুষার",
    "match-q3":             "৩. ভ্রমণের দূরত্ব?",
    "match-opt-domestic":   "ভারতের মধ্যে",
    "match-opt-intl":       "আন্তর্জাতিক",
    "match-btn":            "আমাকে ম্যাচ করুন!",
    "match-result-h2":      "একটি ম্যাচ পাওয়া গেছে!",
    "match-no-results-h3":  "কোনো মিল পাওয়া যায়নি 😕",
    "match-no-results-p":   "দয়া করে আপনার পছন্দ পরিবর্তন করে দেখুন।",
    "match-check-budget":   "বাজেট পরীক্ষা করুন",

    /* ── PAGE 3 – WEATHER RESULTS ── */
    "weather-result-hot":     "গরম / ক্রান্তীয় গন্তব্য",
    "weather-result-pleasant":"মৃদু / আনন্দদায়ক গন্তব্য",
    "weather-result-cold":    "ঠান্ডা / তুষারময় গন্তব্য",
    "weather-result-rainy":   "আর্দ্র / বৃষ্টিময় গন্তব্য",

    /* ── PAGE 4 – BUDGET ── */
    "budget-opt-custom": "-- কাস্টম / অন্যান্য --",

    /* ── PAGE 5 – SEASONAL ── */
    "seasonal-h1":          "মৌসুমি বিশেষ",
    "seasonal-subtitle":    "২০২৬ সালের অনন্য অভিজ্ঞতা",
    "seasonal-h2":          "এই মাসের বিশেষ আকর্ষণ",
    "season-best-time":     "সেরা সময়:",
    "season-badge-adventure":   "অ্যাডভেঞ্চার",
    "season-badge-culture":     "সংস্কৃতি",
    "season-badge-romantic":    "রোমান্টিক",
    "season-badge-relaxation":  "বিশ্রাম",
    "season-badge-wellness":    "সুস্থতা",
    "season-badge-heritage":    "ঐতিহ্য",
    "season-badge-skiing":      "স্কিইং",
    "season-badge-luxury":      "বিলাসবহুল",
    "season-badge-nature":      "প্রকৃতি",
    "season-ladakh-name":    "লেহ লাদাখ, ভারত",
    "season-ladakh-time":    "জুন থেকে সেপ্টেম্বর",
    "season-ladakh-desc":    "উচ্চ-উচ্চতার মঠ এবং মনোমুগ্ধকর প্যাংগং লেক অনুভব করুন।",
    "season-tokyo-name":     "টোকিও, জাপান",
    "season-tokyo-time":     "মার্চ থেকে এপ্রিল",
    "season-tokyo-desc":     "জনপ্রিয় চেরি ব্লসম এবং প্রাণবন্ত শহুরে জীবন উপভোগ করুন।",
    "season-paris-name":     "প্যারিস, ফ্রান্স",
    "season-paris-time":     "জুন থেকে আগস্ট",
    "season-paris-desc":     "সুন্দর গ্রীষ্মকালীন মৌসুমে 'আলোর শহর' উপভোগ করুন।",
    "season-santorini-name": "সান্তোরিনি, গ্রীস",
    "season-santorini-time": "এপ্রিল থেকে অক্টোবর",
    "season-santorini-desc": "এজিয়ান সাগরের তীরে সাদা-ধোয়া স্থাপত্যের অপূর্ব দৃশ্য।",
    "season-bali-name":      "বালি, ইন্দোনেশিয়া",
    "season-bali-time":      "মে থেকে সেপ্টেম্বর",
    "season-bali-desc":      "উবুদে আধ্যাত্মিক আশ্রয় এবং সবুজ ধানক্ষেত।",
    "season-jaipur-name":    "জয়পুর, ভারত",
    "season-jaipur-time":    "নভেম্বর থেকে ফেব্রুয়ারি",
    "season-jaipur-desc":    "গোলাপী শহরে বিশাল প্রাসাদ ও ঐতিহাসিক দুর্গ অন্বেষণ করুন।",
    "season-zermatt-name":   "জারমাট, সুইজারল্যান্ড",
    "season-zermatt-time":   "ডিসেম্বর থেকে মার্চ",
    "season-zermatt-desc":   "মহাশক্তিশালী ম্যাটারহর্নের পাদদেশে বিশ্বমানের শীতকালীন খেলাধুলা।",
    "season-positano-name":  "পোজিতানো, ইতালি",
    "season-positano-time":  "মে থেকে সেপ্টেম্বর",
    "season-positano-desc":  "আশ্চর্যজনক উপকূলীয় পাহাড় এবং বিলাসবহুল ইতালীয় সৈকত জীবন।",
    "season-munnar-name":    "মুন্নার, ভারত",
    "season-munnar-time":    "সেপ্টেম্বর থেকে মার্চ",
    "season-munnar-desc":    "চা বাগান এবং কুয়াশাচ্ছন্ন পাহাড়ের মাঝে বিশ্রাম নিন।",
    "season-reykjavik-name": "রেইকজাভিক, আইসল্যান্ড",
    "season-reykjavik-time": "সেপ্টেম্বর থেকে মার্চ",
    "season-reykjavik-desc": "জাদুকরী নর্দার্ন লাইটস দেখার জন্য আদর্শ স্থান।",

    /* ── PAGE 6 – CONTACT ── */
    "contact-subtitle":           "যোগাযোগ করুন",
    "contact-h2":                 "আমাদের সাথে যোগাযোগ করুন",
    "contact-intro":              "আপনার ২০২৬ ভ্রমণ পরিকল্পনা নিয়ে প্রশ্ন আছে? আমাদের দল আপনাদের সাহায্য করতে প্রস্তুত।",
    "contact-email-lbl":          "ইমেইল ঠিকানা",
    "contact-phone-lbl":          "ফোন নম্বর",
    "contact-office-lbl":         "অফিসের অবস্থান",
    "contact-fname":              "পুরো নাম",
    "contact-emailid":            "ইমেইল আইডি",
    "contact-message":            "বার্তা",
    "contact-message-placeholder":"আমরা কীভাবে আপনাকে সাহায্য করতে পারি?",
    "contact-btn":                "বার্তা পাঠান",
    "contact-highlight":          "কোথায় যাবেন দেখতে চান? আমাদের দেখুন",
    "contact-highlight-link":     "গন্তব্য তালিকা",

    /* ── PAGE 7 – ABOUT ── */
    "about-subtitle":       "কেন আমাদের বেছে নেবেন",
    "about-h2":             "আপনার স্মার্ট ভ্রমণ সঙ্গী",
    "about-intro":          "TravelAssistant সেই ভ্রমণকারীদের জন্য তৈরি যারা পরিকল্পনায় স্পষ্টতা ও আত্মবিশ্বাস চান।",
    "about-feat1-title":    "🌦 আবহাওয়াভিত্তিক পরিকল্পনা",
    "about-feat1-desc":     "আপনার পছন্দের জলবায়ু অনুযায়ী গন্তব্য বেছে নিন।",
    "about-feat2-title":    "💰 স্মার্ট বাজেট অনুমান",
    "about-feat2-desc":     "আমাদের বাজেট প্ল্যানার INR-তে বাস্তবসম্মত খরচের অনুমান দেয়।",
    "about-feat3-title":    "🌍 কিউরেটেড গন্তব্য",
    "about-feat3-desc":     "আমরা জনপ্রিয় ও নির্ভরযোগ্য গন্তব্যগুলো সাবধানে বেছে রাখি।",
    "about-feat4-title":    "📅 মৌসুমি সুপারিশ",
    "about-feat4-desc":     "নির্দিষ্ট মৌসুমে সেরা গন্তব্যগুলো আবিষ্কার করুন।",
    "about-feat5-title":    "🚀 সহজ ও ব্যবহারকারী-বান্ধব",
    "about-feat5-desc":     "সহজ নেভিগেশন ও দ্রুত তথ্য অ্যাক্সেস।",
    "about-feat6-title":    "🔓 অতিথি-বান্ধব অ্যাক্সেস",
    "about-feat6-desc":     "বাধ্যতামূলক নিবন্ধন ছাড়াই গন্তব্য অন্বেষণ করুন।",
    "about-highlight":      "স্মার্টভাবে পরিকল্পনা শুরু করুন — আমাদের দেখুন",
    "about-highlight-link": "গন্তব্য",

    /* ── PAGE 10 – PACKING ── */
    "pack-subtitle":     "আপনার স্মার্ট যাত্রা এখানেই শুরু",
    "pack-h2":           "স্মার্ট প্যাকিং সহায়ক",
    "pack-dest-label":   "গন্তব্য:",
    "pack-dest-none":    "নির্বাচিত হয়নি",
    "pack-label-days":   "ভ্রমণের সময়কাল",
    "pack-opt-3days":    "২–৩ দিন",
    "pack-opt-5days":    "৪–৬ দিন",
    "pack-opt-8days":    "৭+ দিন",
    "pack-label-climate":"জলবায়ু",
    "pack-opt-hot":      "গরম / ক্রান্তীয়",
    "pack-opt-mild":     "মৃদু / আনন্দদায়ক",
    "pack-opt-cold":     "ঠান্ডা / তুষার",
    "pack-label-type":   "ভ্রমণের ধরন",
    "pack-opt-domestic": "অভ্যন্তরীণ",
    "pack-opt-intl":     "আন্তর্জাতিক",
    "pack-btn":          "প্যাকিং তালিকা তৈরি করুন",
    "pack-checklist-h2": "আপনার প্যাকিং চেকলিস্ট",

    /* ── PACKING CATEGORIES ── */
    "pack-cat-clothing":   "👕 পোশাক-আশাক",
    "pack-cat-essentials": "🎒 প্রয়োজনীয় জিনিসপত্র ও নথি",
    "pack-cat-health":     "🩺 স্বাস্থ্য ও নিরাপত্তা",
    "pack-cat-extras":     "✨ অতিরিক্ত",

    /* ── PACKING ITEMS ── */
    "pack-item-comfortable":  "আরামদায়ক পোশাক",
    "pack-item-sleepwear":    "ঘুমানোর পোশাক",
    "pack-item-innerwear":    "অন্তর্বাস",
    "pack-item-cotton":       "সুতির কাপড়",
    "pack-item-cap":          "টুপি",
    "pack-item-sunglasses":   "রোদচশমা",
    "pack-item-jacket":       "হালকা জ্যাকেট",
    "pack-item-casual":       "ক্যাজুয়াল পোশাক",
    "pack-item-heavy-jacket": "জ্যাকেট",
    "pack-item-thermals":     "থার্মাল পোশাক",
    "pack-item-gloves":       "দস্তানা",
    "pack-item-socks":        "উলের মোজা",
    "pack-item-phone":        "মোবাইল ফোন",
    "pack-item-charger":      "চার্জার",
    "pack-item-powerbank":    "পাওয়ার ব্যাংক",
    "pack-item-passport":     "পাসপোর্ট",
    "pack-item-visa":         "ভিসা",
    "pack-item-sim":          "আন্তর্জাতিক সিম",
    "pack-item-footwear":     "অতিরিক্ত জুতা",
    "pack-item-laundry":      "লন্ড্রি ব্যাগ",
    "pack-item-medicine":     "প্রাথমিক ঔষধ",
    "pack-item-firstaid":     "প্রাথমিক চিকিৎসার কিট",
    "pack-item-sunscreen":    "সানস্ক্রিন",
    "pack-item-insect":       "পোকামাকড় নিরোধক",
    "pack-item-coldcream":    "কোল্ড ক্রিম",
    "pack-item-lipbalm":      "লিপবাম",
    "pack-item-camera":       "ক্যামেরা",
    "pack-item-docs":         "ভ্রমণের নথি",
    "pack-item-snacks":       "খাবার/স্ন্যাকস",
    "pack-item-swimwear":     "সাঁতারের পোশাক",
    "pack-item-towel":        "তোয়ালে",
    "pack-item-tickets":      "বিমানের টিকিট",
    "pack-item-hotel-conf":   "হোটেল বুকিং কনফার্মেশন",
    "pack-item-id-card":      "আধার কার্ড / ভোটার আইডি",
    "pack-item-insurance":    "ভ্রমণ বীমা",

    /* ── DESTINATION NAMES, DESCS & CLIMATES ── */
    "agra-name":"আগ্রা, ভারত", "agra-desc":"তাজমহলের শাশ্বত সৌন্দর্য।", "agra-climate":"গরম ও শুষ্ক",
    "paris-name":"প্যারিস, ফ্রান্স", "paris-desc":"আইফেল টাওয়ার, মিউজিয়াম ও ক্যাফে সংস্কৃতি।", "paris-climate":"আনন্দদায়ক",
    "rome-name":"রোম, ইতালি", "rome-desc":"কোলোসিয়াম, ভ্যাটিকান ও প্রাচীন ধ্বংসাবশেষ।", "rome-climate":"মৃদু",
    "kyoto-name":"কিয়োটো, জাপান", "kyoto-desc":"মন্দির, চেরি ব্লসম এবং ঐতিহ্য।", "kyoto-climate":"মৃদু",
    "kolkata-name":"কলকাতা, ভারত", "kolkata-desc":"ঔপনিবেশিক স্থাপত্য ও সাংস্কৃতিক কেন্দ্র।", "kolkata-climate":"আর্দ্র",
    "athens-name":"এথেন্স, গ্রীস", "athens-desc":"পাশ্চাত্য সভ্যতার জন্মস্থান।", "athens-climate":"রৌদ্রোজ্জ্বল",
    "manali-name":"মানালি, ভারত", "manali-desc":"তুষার ক্রীড়া এবং ট্রেকিং রুট।", "manali-climate":"ঠান্ডা",
    "kashmir-name":"কাশ্মীর, ভারত", "kashmir-desc":"ডাল লেক এবং তুষার উপত্যকা।", "kashmir-climate":"ঠান্ডা",
    "swissalps-name":"সুইস আল্পস, সুইজারল্যান্ড", "swissalps-desc":"স্কি রিসোর্ট এবং হিমবাহ।", "swissalps-climate":"ঠান্ডা",
    "ladakh-name":"লেহ-লাদাখ, ভারত", "ladakh-desc":"উচ্চ-উচ্চতার মরুভূমি ল্যান্ডস্কেপ।", "ladakh-climate":"ঠান্ডা",
    "queenstown-name":"কুইন্সটাউন, নিউজিল্যান্ড", "queenstown-desc":"বিশ্বের অ্যাডভেঞ্চারের রাজধানী।", "queenstown-climate":"মৃদু",
    "zermatt-name":"জারমাট, সুইজারল্যান্ড", "zermatt-desc":"ম্যাটারহর্ন পাহাড়ের দৃশ্য।", "zermatt-climate":"ঠান্ডা",
    "goa-name":"গোয়া, ভারত", "goa-desc":"সমুদ্র সৈকত এবং নাইটলাইফ।", "goa-climate":"গরম ও আর্দ্র",
    "maldives-name":"মালদ্বীপ", "maldives-desc":"বিলাসবহুল ওভারওয়াটার ভিলা।", "maldives-climate":"ক্রান্তীয়",
    "phuket-name":"ফুকেট, থাইল্যান্ড", "phuket-desc":"দ্বীপ ভ্রমণ এবং সমুদ্র সৈকত।", "phuket-climate":"গরম",
    "kerala-name":"কেরালা ব্যাকওয়াটার্স, ভারত", "kerala-desc":"হাউসবোট এবং নারকেল গাছ।", "kerala-climate":"বৃষ্টিময় ও আনন্দদায়ক",
    "hawaii-name":"হাওয়াই, আমেরিকা", "hawaii-desc":"আগ্নেয়গিরি এবং সার্ফিং।", "hawaii-climate":"উষ্ণ",
    "bali-name":"বালি, ইন্দোনেশিয়া", "bali-desc":"সমুদ্র সৈকত এবং মন্দির।", "bali-climate":"ক্রান্তীয়",
    "newyork-name":"নিউ ইয়র্ক, আমেরিকা", "newyork-desc":"আকাশচুম্বী ভবন এবং ব্রডওয়ে।", "newyork-climate":"পরিবর্তনশীল",
    "mumbai-name":"মুম্বাই, ভারত", "mumbai-desc":"বলিউড এবং রাস্তার বাজার।", "mumbai-climate":"গরম",
    "london-name":"লন্ডন, যুক্তরাজ্য", "london-desc":"প্রাসাদ এবং জাদুঘর।", "london-climate":"শীতল",
    "delhi-name":"দিল্লি, ভারত", "delhi-desc":"ঐতিহাসিক দুর্গ এবং বাজার।", "delhi-climate":"গরম",
    "singapore-name":"সিঙ্গাপুর", "singapore-desc":"পরিচ্ছন্ন আধুনিক শহর ও বাগান।", "singapore-climate":"গরম",
    "dubai-name":"দুবাই, সংযুক্ত আরব আমিরাত", "dubai-desc":"আকাশচুম্বী ভবন এবং মরুভূমি সাফারি।", "dubai-climate":"গরম"
  }
};

// ── TOGGLE BUTTON ACTIVE STATE ──
function updateToggleButtons(lang) {
  const btnEn = document.getElementById("lang-btn-en");
  const btnBn = document.getElementById("lang-btn-bn");
  if (!btnEn || !btnBn) return;
  if (lang === "bn") {
    btnBn.style.background = "#007bff"; btnBn.style.color = "white";
    btnEn.style.background = "transparent"; btnEn.style.color = "#007bff";
  } else {
    btnEn.style.background = "#007bff"; btnEn.style.color = "white";
    btnBn.style.background = "transparent"; btnBn.style.color = "#007bff";
  }
}

// ── SET LANGUAGE ──
function setLanguage(lang) {
  localStorage.setItem("lang", lang);
  const t = translations[lang];

  document.querySelectorAll("[data-i18n]").forEach(el => {
    const key = el.getAttribute("data-i18n");
    if (t[key] !== undefined) el.innerText = t[key];
  });

  document.querySelectorAll("[data-i18n-placeholder]").forEach(el => {
    const key = el.getAttribute("data-i18n-placeholder");
    if (t[key] !== undefined) el.placeholder = t[key];
  });

  updateToggleButtons(lang);

  // Fire event so pages can re-render dynamic content
  document.dispatchEvent(new CustomEvent("languageChanged", { detail: { lang } }));
}

// ── AUTO-LOAD ON PAGE START ──
(function () {
  const savedLang = localStorage.getItem("lang") || "en";
  window.addEventListener("DOMContentLoaded", () => setLanguage(savedLang));
})();
